#!/usr/bin/env bash
# a command that shows all listening ports
if [ $# == 1 ]; then
    for _ in {1..5};
    do
        ping $1
    done
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi